config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: :json} do
    resources :messages, only: [:create]
  end
  resources :messages, only: [:index]
  resources :hashtags, only: [:show]
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  validates_presence_of :hashtag

  has_many :taggings

  has_many :messages, through: :taggings, source: :message

  def self.update_hashtags(hashtags, message_id)
    hashtags.each do |htext|
      @hashtag = Hashtag.find_by_hashtag(htext)
      if @hashtag
        count = @hashtag[:count]
        @hashtag.update({count: (count + 1)})
        Tagging.create({message_id: message_id, hashtag_id: @hashtag.id})
      else
        @hashtag = Hashtag.new({hashtag: htext, count: 1})
        if @hashtag.save
          Tagging.create({message_id: message_id, hashtag_id: @hashtag.id})
        end
      end
    end
  end



end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, presence: true, length: { maximum: 141 }

  has_many :taggings

  has_many :hashtags, through: :taggings, source: :hashtag

  def extract_hashtags
    self.body.scan(/\#\w*/)
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  validates_presence_of :message_id, :hashtag_id

  belongs_to :hashtag
  belongs_to :message

end

app/controllers/api/messages_controller.rb
require 'byebug'
class Api::MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    hashtags = @message.extract_hashtags
    if @message.save
      Hashtag.update_hashtags(hashtags, @message.id)
      redirect_to :messages
    else
      render json: {errors: @message.errors.full_messages}, status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def index
  end
  
  def show
    @hashtag = Hashtag.find(params[:id])
    @messages = @hashtag.messages
    render :show
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all.order(created_at: :desc)
    @hashtags = Hashtag.all.order(count: :desc)
    render :index
  end

end

app/helpers/api/messages_helper.rb
module Api::MessagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtag_helper.rb
module HashtagHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/hashtags/show.html.erb
<div class="hash-messages">

  <h2>Messages for <%= @hashtag.hashtag %></h2>

  <ul>
    <% @messages.each do |msg| %>
    <li><%= msg.body %></li>
    <% end %>
  </ul>

  <%= link_to "Back to Messages", messages_url %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Zozi Messages</h1>
    <%= form_for Message.new, url: "api/messages", html: {class: "new-message"} do |f| %>
      <%= f.text_area :body, maxlength: 141, required: true, placeholder: "Enter a message < 141 characters" %>
      <br>
      <%= f.submit "Create" %>
    <% end %>

  </header>
<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<div class="wrapper">

  <section class="messages-section">
    <h3>Recent Messages</h3>
    <ul class="messages">
      <% if @messages.empty? %>
        <li>No messages yet...add one!</li>
      <% else %>
        <% @messages.each do |message| %>
          <li><%= message.body %></li>
        <% end %>
      <% end %>
    </ul>
  </section>

  <section class="hashtags-section">
    <h3>Hashtags</h3>
    <ul class="hashtags">
      <% @hashtags.each do |hashtag| %>
        <li><%= link_to hashtag.hashtag, hashtag %> - <%= hashtag.count %> <%= hashtag.count > 1 ? "occurances" : "occurance" %></li>
      <% end %>
    </ul>
  </section>

</div>